meta:
  title: Oğuzcan Demircan
  author: Oğuzcan Demircan
  owner: Oğuzcan Demircan
  generator: Oğuzcan Demircan
  # description: laravel, php, vuejs, javascript etc. my thinking about programming languages, frameworks, technologies, and various other things.
  description: laravel, php, docker, vuejs, javascript vb. programlama dilleri, frameworkleri, teknolojileri ve diğer çeşitli alanlar hakkındaki bilgi, düşünce ve deneyimlerimi içeren blog.
  keywords: oguzcandemircan, oğuzcan demircan, laravel, developer, backend, php, docker, yazılım, açık kaynak, software developer, open source, vue js, javascript, yazılım geliştirici, geliştirici

navs:
- name: anasayfa
  url: /

- name: makaleler
  url: /

# - name: etiketler
#   url: /etiketler

- name: kategoriler
  url: /kategoriler

- name: hakkımda
  url: /hakkimda

disqus:
  active: true
  username: oguzcandemircan

loader: 
  active: false
  text: "Oğuzcan Demrican"

url: "https://oguzcandemircan.com"
permalink: :title
default_language: tr

author: 
  name: Oğuzcan Demircan
  first_name: Oğuzcan
  last_name: Demircan
  title: Software Developer
  image: /assets/images/oguzcan-demircan.jpg
  email: oguzcandemircan@gmail.com
  twitter: oguzcandemircan
  github: oguzcandemircan
  gitlab: oguzcandemircan
  medium: oguzcandemircan
  linkedin: oguzcandemircan
  gender: male

footer:
  text: © 2019 Oğuzcan Demircan All Rights Reserved

plugins:
  - jekyll-sitemap
  - jekyll-feed

google:
  site_verification: wzOppR9AsH2034ojvcyoE981gi2ux8R27lO4wJXY6pk
  tracking_number: UA-137191559-1

yandex:
  site_verification: e32936656b1e1458

analytics:
  active: false